# Generated by Django 6.0.5 on 2026-05-28 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP ERP (Fuel/Procurement)'), ('UTILITY', 'Utility Portal (Electricity)'), ('TRAVEL', 'Travel API (Concur/Navan)')], max_length=20)),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 (Direct)'), ('SCOPE_2', 'Scope 2 (Indirect - Utilities)'), ('SCOPE_3', 'Scope 3 (Value Chain - Travel/Procurement)')], max_length=20)),
                ('raw_data', models.JSONField(help_text='The exact, unedited row as it arrived from the source')),
                ('is_edited', models.BooleanField(default=False, help_text='Has an analyst modified this after ingestion?')),
                ('normalized_value', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('normalized_unit', models.CharField(blank=True, help_text='e.g., kg CO2e, kWh', max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('FLAGGED', 'Suspicious / Flagged'), ('APPROVED', 'Approved by Analyst'), ('LOCKED', 'Locked for Audit')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.tenant')),
            ],
        ),
    ]
