# Generated by Django 5.1.5 on 2026-05-28 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emissionrecord",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="emissionrecord",
            name="description",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Human-readable label, e.g. 'Diesel Fuel', 'JFK-LHR Flight'",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="emissionrecord",
            name="flag_reason",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Why this row was flagged (missing data, parse error, outlier)",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="emissionrecord",
            name="original_unit",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The unit as it appeared in the raw source before normalization",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="emissionrecord",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emissionrecord",
            name="reviewed_by",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Analyst who approved/locked this record",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="emissionrecord",
            name="normalized_unit",
            field=models.CharField(
                blank=True,
                help_text="Standardized unit after conversion (kWh, liters, km, nights)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="emissionrecord",
            name="raw_data",
            field=models.JSONField(
                help_text="The exact, unmodified row as received from the source"
            ),
        ),
        migrations.AlterField(
            model_name="emissionrecord",
            name="scope",
            field=models.CharField(
                choices=[
                    ("SCOPE_1", "Scope 1 (Direct)"),
                    ("SCOPE_2", "Scope 2 (Indirect - Energy)"),
                    ("SCOPE_3", "Scope 3 (Value Chain)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="emissionrecord",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("SAP", "SAP Flat File (Fuel/Procurement)"),
                    ("UTILITY", "Utility Portal CSV (Electricity)"),
                    ("TRAVEL", "Travel Platform JSON (Flights/Hotels/Ground)"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name="IngestionBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source_type", models.CharField(max_length=20)),
                ("file_name", models.CharField(blank=True, default="", max_length=255)),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                ("row_count", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="batches",
                        to="ingestion.tenant",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="emissionrecord",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                help_text="The upload batch that produced this row",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records",
                to="ingestion.ingestionbatch",
            ),
        ),
    ]
